// React/src/layouts/side-nav-inner-toolbar/side-nav-inner-toolbar.js
import Button from 'devextreme-react/button';
import Drawer from 'devextreme-react/drawer';
import ScrollView from 'devextreme-react/scroll-view';
import Toolbar, { Item } from 'devextreme-react/toolbar';
import React, { useState, useCallback, useRef } from 'react';
import { useNavigate } from 'react-router';
import { Header, SideNavigationMenu, Footer } from '../../components';
import './side-nav-inner-toolbar.scss';
import { useScreenSize } from '../../utils/media-query';
import { Template } from 'devextreme-react/core/template';
import { useMenuPatch } from '../../utils/patches';




export default function SideNavInnerToolbar({ title, children }) {
  const scrollViewRef = useRef(null);
  const navigate = useNavigate();
  const { isXSmall, isLarge } = useScreenSize();
  const [patchCssClass, onMenuReady] = useMenuPatch();
  const [menuStatus, setMenuStatus] = useState(
    isLarge ? MenuStatus.Opened : MenuStatus.Closed
  );

  const toggleMenu = useCallback(({ event }) => {
    setMenuStatus(
      prevMenuStatus => prevMenuStatus === MenuStatus.Closed
        ? MenuStatus.Opened
        : MenuStatus.Closed
    );
    event.stopPropagation();
  }, []);

  const temporaryOpenMenu = useCallback(() => {
    setMenuStatus(
      prevMenuStatus => prevMenuStatus === MenuStatus.Closed
        ? MenuStatus.TemporaryOpened
        : prevMenuStatus
    );
  }, []);

  const onOutsideClick = useCallback(() => {
    setMenuStatus(
      prevMenuStatus => prevMenuStatus !== MenuStatus.Closed && !isLarge
        ? MenuStatus.Closed
        : prevMenuStatus
    );
    return true;
  }, [isLarge]);

  const onNavigationChanged = useCallback(({ itemData, event, node }) => {
    if (menuStatus === MenuStatus.Closed || !itemData.path || node.selected) {
      event.preventDefault();
      return;
    }

    navigate(itemData.path);
    scrollViewRef.current.instance.scrollTo(0);

    if (!isLarge || menuStatus === MenuStatus.TemporaryOpened) {
      setMenuStatus(MenuStatus.Closed);
      event.stopPropagation();
    }
  }, [navigate, menuStatus, isLarge]);

  return (
    <div className={'side-nav-inner-toolbar'}>
      <Drawer
        className={['drawer', patchCssClass].join(' ')}
        position={'before'}
        closeOnOutsideClick={onOutsideClick}
        openedStateMode={isLarge ? 'shrink' : 'overlap'}
        revealMode={isXSmall ? 'slide' : 'expand'}
        minSize={isXSmall ? 0 : 60}
        maxSize={250}
        shading={isLarge ? false : true}
        opened={menuStatus === MenuStatus.Closed ? false : true}
        template={'menu'}
      >
        <div className={'container'}>
          <Header
            menuToggleEnabled={isXSmall}
            toggleMenu={toggleMenu}
          />
          <ScrollView ref={scrollViewRef} className={'layout-body with-footer'}>
            <div className={'content'}>
              {React.Children.map(children, (item) => {
                return item.type !== Footer && item;
              })}
            </div>
            <div className={'content-block'}>
              {React.Children.map(children, (item) => {
                return item.type === Footer && item;
              })}
            </div>
          </ScrollView>
        </div>
        <Template name={'menu'}>
          <SideNavigationMenu
            compactMode={menuStatus === MenuStatus.Closed}
            selectedItemChanged={onNavigationChanged}
            openMenu={temporaryOpenMenu}
            onMenuReady={onMenuReady}
          >
            <Toolbar id={'navigation-header'}>
              {
                !isXSmall &&
                <Item
                  location={'before'}
                  cssClass={'menu-button'}
                >
                  <Button icon="menu" stylingMode="text" onClick={toggleMenu} />
                </Item>
              }
              <Item location={'before'} cssClass={'header-title'} text={title} />
            </Toolbar>
          </SideNavigationMenu>
        </Template>
      </Drawer>
    </div>
  );
}

const MenuStatus = {
  Closed: 1,
  Opened: 2,
  TemporaryOpened: 3
};

// Vue/src/layouts/side-nav-inner-toolbar.vue
<template>
  <div class="side-nav-inner-toolbar dx-theme-background-color">
    <DxDrawer
      class="drawer"
      position="before"
      template="menuTemplate"
      v-model:opened="menuOpened"
      :opened-state-mode="drawerOptions.openedStateMode"
      :reveal-mode="drawerOptions.revealMode"
      :min-size="drawerOptions.minSize"
      :max-size="drawerOptions.maxSize"
      :shading="drawerOptions.shading"
      :close-on-outside-click="drawerOptions.closeOnOutsideClick"
    >
      <div class="container dx-theme-background-color">
        <HeaderToolbar
          :menu-toggle-enabled="headerMenuTogglerEnabled"
          :toggle-menu-func="toggleMenu"
        />
        <DxScrollView
          ref="scrollViewRef"
          class="layout-body with-footer"
        >
          <slot/>
          <slot name="footer"/>
        </DxScrollView>
      </div>
      <template #menuTemplate>
        <SideNavMenu
          :compact-mode="!menuOpened"
          @click="handleSideBarClick"
        >
          <DxToolbar id="navigation-header">
            <DxItem
              v-if="!isXSmall"
              location="before"
              css-class="dx-theme-text-color"
            >
              <template #default>
                <DxButton
                  icon="menu"
                  styling-mode="text"
                  @click="toggleMenu"
                />
              </template>
            </DxItem>
            <DxItem
              location="before"
              css-class="header-title dx-toolbar-label"
            >
              <template #default>
                <div>{{ title }}</div>
              </template>
            </DxItem>
          </DxToolbar>
        </SideNavMenu>
      </template>
    </DxDrawer>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import { useRoute } from 'vue-router';
import DxButton, { type DxButtonTypes } from 'devextreme-vue/button';
import DxDrawer, { type DxDrawerTypes } from 'devextreme-vue/drawer';
import DxScrollView from 'devextreme-vue/scroll-view';
import DxToolbar, { DxItem } from 'devextreme-vue/toolbar';
import HeaderToolbar from '../components/header-toolbar.vue';
import SideNavMenu from '../components/side-nav-menu.vue';

const props = defineProps<{
  title: string;
  isXSmall: boolean;
  isLarge: boolean;
}>();

const route = useRoute();

const scrollViewRef = ref<any>(null);
const menuOpened = ref(props.isLarge);
const menuTemporaryOpened = ref(false);

function toggleMenu(e: DxButtonTypes.ClickEvent): void {
  const pointerEvent = e.event;
  pointerEvent?.stopPropagation();
  if (menuOpened.value) {
    menuTemporaryOpened.value = false;
  }

  menuOpened.value = !menuOpened.value;
}

function handleSideBarClick() {
  if (menuOpened.value === false) {
    menuTemporaryOpened.value = true;
  }

  menuOpened.value = true;
}

type DrawerPropsExt = DxDrawerTypes.Properties & {
  closeOnOutsideClick: boolean;
};

const drawerOptions = computed<DrawerPropsExt>(() => {
  const shaderEnabled = !props.isLarge;
  return {
    openedStateMode: props.isLarge ? 'shrink' : 'overlap',
    revealMode: props.isXSmall ? 'slide' : 'expand',
    minSize: props.isXSmall ? 0 : 60,
    maxSize: props.isXSmall ? 250 : undefined,
    closeOnOutsideClick: shaderEnabled,
    shading: shaderEnabled,
  };
});

const headerMenuTogglerEnabled = computed(() => {
  return props.isXSmall;
});

watch(
  () => props.isLarge,
  () => {
    if (!menuTemporaryOpened.value) {
      menuOpened.value = props.isLarge;
    }
  }
);

watch(
  () => route.path,
  () => {
    if (menuTemporaryOpened.value || !props.isLarge) {
      menuOpened.value = false;
      menuTemporaryOpened.value = false;
    }
    scrollViewRef.value.instance.scrollTo(0);
  }
);
</script>

<style lang="scss">
.side-nav-inner-toolbar {
  width: 100%;
}

#navigation-header {
  @use "../themes/variables.additional" as *;
  background-color: $base-accent;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);

  .menu-button .dx-icon {
    color: $base-text-color;
  }

  .screen-x-small & {
    padding-left: 20px;
  }

  .dx-theme-generic & {
    padding-top: 10px;
    padding-bottom: 10px;
  }
}
</style>
