// Vue/src/views/change-password-form.vue
<template>
  <form @submit.prevent="onSubmit">
    <DxForm
      :form-data="formData"
      :disabled="loading"
    >
      <DxItem
        data-field="password"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Password', mode: 'password' }"
      >
        <DxRequiredRule message="Password is required"/>
        <DxLabel :visible="false"/>
      </DxItem>
      <DxItem
        data-field="confirmedPassword"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Confirm Password', mode: 'password' }"
      >
        <DxRequiredRule message="Password is required"/>
        <DxCustomRule
          message="Passwords do not match"
          :validation-callback="confirmPassword"
        />
        <DxLabel :visible="false"/>
      </DxItem>
      <DxButtonItem>
        <DxButtonOptions
          width="100%"
          type="default"
          template="changePassword"
          :use-submit-behavior="true"
        />
      </DxButtonItem>

      <template #changePassword>
        <div>
          <span class="dx-button-text">
            <DxLoadIndicator
              v-if="loading"
              width="24px"
              height="24px"
              :visible="true"
            />
            <span v-if="!loading">Continue</span>
          </span>
        </div>
      </template>
    </DxForm>
  </form>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import DxForm, {
  DxItem,
  DxLabel,
  DxButtonItem,
  DxButtonOptions,
  DxCustomRule,
  DxRequiredRule,
} from 'devextreme-vue/form';
import DxLoadIndicator from 'devextreme-vue/load-indicator';
import notify from 'devextreme/ui/notify';
import auth from '../auth';

const router = useRouter();
const route = useRoute();

const recoveryCode = ref('');
const loading = ref(false);
const formData = reactive({
  password: '',
});

recoveryCode.value = route.params.recoveryCode as string;

async function onSubmit() {
  const { password } = formData;
  loading.value = true;

  const result = await auth.changePassword(password, recoveryCode.value);
  loading.value = false;

  if (result.isOk) {
    router.push('/login-form');
  } else {
    notify(result.message, 'error', 2000);
  }
}

function confirmPassword(e: any) {
  return e.value === formData.password;
}
</script>

<style>

</style>

// React/src/components/change-password-form/ChangePasswordForm.tsx
import React, { useState, useRef, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import Form, {
  Item,
  Label,
  ButtonItem,
  ButtonOptions,
  RequiredRule,
  CustomRule,
} from 'devextreme-react/form';
import LoadIndicator from 'devextreme-react/load-indicator';
import notify from 'devextreme/ui/notify';

import { changePassword } from '../../api/auth';

const passwordEditorOptions = { stylingMode: 'filled', placeholder: 'Password', mode: 'password' };
const confirmedPasswordEditorOptions = { stylingMode: 'filled', placeholder: 'Confirm Password', mode: 'password' };

export default function ChangePasswordForm(): JSX.Element {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const formData = useRef({ password: '' });
  const { recoveryCode } = useParams<{ recoveryCode: string }>();

  const handleSubmitAsync = useCallback(async () => {
    const { password } = formData.current;
    setLoading(true);
    const result = await changePassword(password, recoveryCode ?? '');
    setLoading(false);
    if (result.isOk) {
      navigate('/login')?.catch(() => {});
    } else {
      notify(result.message, 'error', 2000);
    }
  }, [navigate, recoveryCode]);

  const onSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    handleSubmitAsync().catch(() => {});
  }, [handleSubmitAsync]);

  const confirmPassword = useCallback(
    ({ value }: { value: string | number }) => value === formData.current.password,
    [],
  );

  return (
    <form onSubmit={onSubmit}>
      <Form formData={formData.current} disabled={loading}>
        <Item
          dataField='password'
          editorType='dxTextBox'
          editorOptions={passwordEditorOptions}
        >
          <RequiredRule message="Password is required" />
          <Label visible={false} />
        </Item>
        <Item
          dataField='confirmedPassword'
          editorType='dxTextBox'
          editorOptions={confirmedPasswordEditorOptions}
        >
          <RequiredRule message="Password is required" />
          <CustomRule
            message='Passwords do not match'
            validationCallback={confirmPassword}
          />
          <Label visible={false} />
        </Item>
        <ButtonItem>
          <ButtonOptions
            width='100%'
            type='default'
            useSubmitBehavior={true}
          >
            <span className="dx-button-text">
              {
                loading
                  ? <LoadIndicator width='24px' height='24px' visible={true} />
                  : 'Continue'
              }
            </span>
          </ButtonOptions>
        </ButtonItem>
      </Form>
    </form>
  );
}
