// Vue/src/views/login-form.vue
<template>
  <form
    class="login-form"
    @submit.prevent="onSubmit"
  >
    <DxForm
      :form-data="formData"
      :disabled="loading"
    >
      <DxItem
        data-field="email"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Email', mode: 'email' }"
      >
        <DxRequiredRule message="Email is required"/>
        <DxEmailRule message="Email is invalid"/>
        <DxLabel :visible="false"/>
      </DxItem>
      <DxItem
        data-field="password"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Password', mode: 'password' }"
      >
        <DxRequiredRule message="Password is required"/>
        <DxLabel :visible="false"/>
      </DxItem>
      <DxItem
        data-field="rememberMe"
        editor-type="dxCheckBox"
        :editor-options="{ text: 'Remember me', elementAttr: { class: 'form-text' } }"
      >
        <DxLabel :visible="false"/>
      </DxItem>
      <DxButtonItem>
        <DxButtonOptions
          width="100%"
          type="default"
          template="signInTemplate"
          :use-submit-behavior="true"
        />
      </DxButtonItem>
      <DxItem>
        <template #default>
          <div class="link">
            <router-link to="/reset-password">Forgot password?</router-link>
          </div>
        </template>
      </DxItem>
      <DxButtonItem>
        <DxButtonOptions
          text="Create an account"
          width="100%"
          :on-click="onCreateAccountClick"
        />
      </DxButtonItem>
      <template #signInTemplate>
        <div>
          <span class="dx-button-text">
            <DxLoadIndicator
              v-if="loading"
              width="24px"
              height="24px"
              :visible="true"
            />
            <span v-if="!loading">Sign In</span>
          </span>
        </div>
      </template>
    </DxForm>
  </form>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import DxLoadIndicator from 'devextreme-vue/load-indicator';
import DxForm, {
  DxItem,
  DxEmailRule,
  DxRequiredRule,
  DxLabel,
  DxButtonItem,
  DxButtonOptions,
} from 'devextreme-vue/form';
import notify from 'devextreme/ui/notify';
import auth from '../auth';

const route = useRoute();
const router = useRouter();

const formData = reactive({
  email: '',
  password: '',
});
const loading = ref(false);

function onCreateAccountClick() {
  router.push('/create-account');
}

async function onSubmit() {
  const { email, password } = formData;
  loading.value = true;
  const result = await auth.logIn(email, password);
  if (!result.isOk) {
    loading.value = false;
    notify(result.message, 'error', 2000);
  } else {
    router.push((route.query.redirect as string) || '/home');
  }
}
</script>

<style lang="scss">
@use "../themes/variables.base" as *;

.login-form {
  .link {
    text-align: center;
    font-size: 16px;
    font-style: normal;

    a {
      text-decoration: none;
    }
  }

  .form-text {
    margin: 10px 0;
    color: $base-text-color;
    opacity: 0.7;
  }
}
</style>

// React/src/components/login-form/LoginForm.tsx
import React, { useState, useRef, useCallback } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Form, {
  Item,
  Label,
  ButtonItem,
  ButtonOptions,
  RequiredRule,
  EmailRule,
} from 'devextreme-react/form';
import LoadIndicator from 'devextreme-react/load-indicator';
import notify from 'devextreme/ui/notify';
import { useAuth } from '../../contexts/auth';

import './LoginForm.scss';

const emailEditorOptions = { stylingMode: 'filled', placeholder: 'Email', mode: 'email' };
const passwordEditorOptions = { stylingMode: 'filled', placeholder: 'Password', mode: 'password' };
const rememberMeEditorOptions = { text: 'Remember me', elementAttr: { class: 'form-text' } };

export default function LoginForm(): JSX.Element {
  const navigate = useNavigate();
  const { signIn } = useAuth();
  const [loading, setLoading] = useState(false);
  const formData = useRef({ email: '', password: '' });

  const handleSubmitAsync = useCallback(async () => {
    const { email, password } = formData.current;
    setLoading(true);

    const result = await signIn(email, password);
    if (!result.isOk) {
      setLoading(false);
      notify(result.message, 'error', 2000);
    }
  }, [signIn]);

  const onSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    handleSubmitAsync().catch(() => {});
  }, [handleSubmitAsync]);

  const onCreateAccountClick = useCallback(() => {
    navigate('/create-account')?.catch(() => {});
  }, [navigate]);

  return (
    <form className='login-form' onSubmit={onSubmit}>
      <Form formData={formData.current} disabled={loading}>
        <Item
          dataField='email'
          editorType='dxTextBox'
          editorOptions={emailEditorOptions}
        >
          <RequiredRule message="Email is required" />
          <EmailRule message="Email is invalid" />
          <Label visible={false} />
        </Item>
        <Item
          dataField='password'
          editorType='dxTextBox'
          editorOptions={passwordEditorOptions}
        >
          <RequiredRule message="Password is required" />
          <Label visible={false} />
        </Item>
        <Item
          dataField='rememberMe'
          editorType='dxCheckBox'
          editorOptions={rememberMeEditorOptions}
        >
          <Label visible={false} />
        </Item>
        <ButtonItem>
          <ButtonOptions
            width='100%'
            type='default'
            useSubmitBehavior={true}
          >
            <span className="dx-button-text">
              {
                loading
                  ? <LoadIndicator width='24px' height='24px' visible={true} />
                  : 'Sign In'
              }
            </span>
          </ButtonOptions>
        </ButtonItem>
        <Item>
          <div className='link'>
            <Link to='/reset-password'>Forgot password?</Link>
          </div>
        </Item>
        <ButtonItem>
          <ButtonOptions
            text='Create an account'
            width='100%'
            onClick={onCreateAccountClick}
          />
        </ButtonItem>
      </Form>
    </form>
  );
}
