// react/src/components/theme-selector/ThemeSelector.js
import React, { useMemo } from 'react';
import SelectBox from 'devextreme-react/select-box';
import ThemeService from '../../utils/theme-service'


export default function ThemeSelector() {
  let themes = ThemeService.getThemeData()
  let currentTheme = ThemeService.getTheme()

  let onValueChanged = (e)=>{
    ThemeService.applyTheme(e.value)
  }
  return (
    <div className={'theme-selector'}>
        <SelectBox
            items={themes}
            value={currentTheme}
            valueExpr="value"
            displayExpr="text"
            onValueChanged={onValueChanged}
        ></SelectBox>
    </div>
  );
}

// angular/src/app/shared/components/theme-selector/theme-selector.component.ts
import { Component, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
import { ThemeService } from '../../services/theme.service';

@Component({
    selector: 'theme-selector',
    templateUrl: 'theme-selector.component.html',
    styleUrls: ['./theme-selector.component.scss']
  })
  
  export class ThemeSelectorComponent {
    currentTheme
    themeSource
    constructor(private theme: ThemeService) {
        this.currentTheme = theme.getTheme()
        this.themeSource = theme.getThemeData()
    }
    onValueChanged(e: any){
        this.theme.applyTheme(e.value)
    }
  
  }
  
  @NgModule({
    imports: [
      CommonModule,
      DxSelectBoxModule
    ],
    declarations: [ ThemeSelectorComponent ],
    exports: [ ThemeSelectorComponent ]
  })
  export class ThemeSelectorModule { }
<dx-select-box
    [items]="themeSource"
    [value]="currentTheme"
    valueExpr="value"
    displayExpr="text"
    (onValueChanged)="onValueChanged($event)"
>

</dx-select-box>
