// vue/src/components/theme-selector.vue
<template>
    <DxSelectBox 
        :items="themeSource"
        :value="currentTheme"
        valueExpr="value"
        displayExpr="text"
        @value-changed="onValueChanged"/>
</template>
<script>
import theme from '../services/theme-service';
import DxSelectBox from 'devextreme-vue/select-box';
export default {
  components: {
    DxSelectBox,
  },
  data() {
    let currentTheme = theme.getTheme()
    let themeSource = theme.getThemeData()
    return {
        currentTheme,
        themeSource
    };
  },
  methods:{
    onValueChanged(e){
      theme.applyTheme(e.value)
    }
  }
};
</script>

// react/src/components/theme-selector/ThemeSelector.js
import React, { useMemo } from 'react';
import SelectBox from 'devextreme-react/select-box';
import ThemeService from '../../utils/theme-service'


export default function ThemeSelector() {
  let themes = ThemeService.getThemeData()
  let currentTheme = ThemeService.getTheme()

  let onValueChanged = (e)=>{
    ThemeService.applyTheme(e.value)
  }
  return (
    <div className={'theme-selector'}>
        <SelectBox
            items={themes}
            value={currentTheme}
            valueExpr="value"
            displayExpr="text"
            onValueChanged={onValueChanged}
        ></SelectBox>
    </div>
  );
}
