// React/src/components/create-account-form/CreateAccountForm.tsx
import React, { useState, useRef, useCallback } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Form, {
  Item,
  Label,
  ButtonItem,
  ButtonOptions,
  RequiredRule,
  CustomRule,
  EmailRule,
} from 'devextreme-react/form';
import notify from 'devextreme/ui/notify';
import LoadIndicator from 'devextreme-react/load-indicator';
import { createAccount } from '../../api/auth';

import './CreateAccountForm.scss';

export default function CreateAccountForm(): JSX.Element {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const formData = useRef({ email: '', password: '' });

  const handleSubmitAsync = useCallback(async () => {
    const { email, password } = formData.current;
    setLoading(true);

    const result = await createAccount(email, password);
    setLoading(false);

    if (result.isOk) {
      navigate('/login')?.catch(() => {});
    } else {
      notify(result.message, 'error', 2000);
    }
  }, [navigate]);

  const onSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    handleSubmitAsync().catch(() => {});
  }, [handleSubmitAsync]);

  const confirmPassword = useCallback(
    ({ value }: { value: string | number }) => value === formData.current.password,
    [],
  );

  return (
    <form className='create-account-form' onSubmit={onSubmit}>
      <Form formData={formData.current} disabled={loading}>
        <Item
          dataField='email'
          editorType='dxTextBox'
          editorOptions={emailEditorOptions}
        >
          <RequiredRule message="Email is required" />
          <EmailRule message="Email is invalid" />
          <Label visible={false} />
        </Item>
        <Item
          dataField='password'
          editorType='dxTextBox'
          editorOptions={passwordEditorOptions}
        >
          <RequiredRule message="Password is required" />
          <Label visible={false} />
        </Item>
        <Item
          dataField='confirmedPassword'
          editorType='dxTextBox'
          editorOptions={confirmedPasswordEditorOptions}
        >
          <RequiredRule message="Password is required" />
          <CustomRule
            message='Passwords do not match'
            validationCallback={confirmPassword}
          />
          <Label visible={false} />
        </Item>
        <Item>
          <div className='policy-info'>
            By creating an account, you agree to the <Link to="#">Terms of Service</Link> and <Link to="#">Privacy Policy</Link>
          </div>
        </Item>
        <ButtonItem>
          <ButtonOptions
            width='100%'
            type='default'
            useSubmitBehavior={true}
          >
            <span className="dx-button-text">
              {
                loading
                  ? <LoadIndicator width='24px' height='24px' visible={true} />
                  : 'Create a new account'
              }
            </span>
          </ButtonOptions>
        </ButtonItem>
        <Item>
          <div className='login-link'>
            Have an account? <Link to='/login'>Sign In</Link>
          </div>
        </Item>
      </Form>
    </form>
  );
}

const emailEditorOptions = { stylingMode: 'filled', placeholder: 'Email', mode: 'email' };
const passwordEditorOptions = { stylingMode: 'filled', placeholder: 'Password', mode: 'password' };
const confirmedPasswordEditorOptions = { stylingMode: 'filled', placeholder: 'Confirm Password', mode: 'password' };

// Vue/src/views/create-account-form.vue
<template>
  <form
    class="create-account-form"
    @submit.prevent="onSubmit"
  >
    <DxForm
      :form-data="formData"
      :disabled="loading"
    >
      <DxItem
        data-field="email"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Email', mode: 'email' }"
      >
        <DxRequiredRule message="Email is required"/>
        <DxEmailRule message="Email is invalid"/>
        <DxLabel :visible="false"/>
      </DxItem>
      <DxItem
        data-field="password"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Password', mode: 'password' }"
      >
        <DxRequiredRule message="Password is required"/>
        <DxLabel :visible="false"/>
      </DxItem>
      <DxItem
        data-field="confirmedPassword"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Confirm Password', mode: 'password' }"
      >
        <DxRequiredRule message="Password is required"/>
        <DxCustomRule
          message="Passwords do not match"
          :validation-callback="confirmPassword"
        />
        <DxLabel :visible="false"/>
      </DxItem>
      <DxItem>
        <template #default>
          <div class="policy-info">
            By creating an account, you agree to the
            <router-link to="#">Terms of Service</router-link>
            and <router-link to="#">Privacy Policy</router-link>
          </div>
        </template>
      </DxItem>
      <DxButtonItem>
        <DxButtonOptions
          width="100%"
          type="default"
          template="createAccount"
          :use-submit-behavior="true"
        />
      </DxButtonItem>
      <DxItem>
        <template #default>
          <div class="login-link">
            Have an account? <router-link to="/login-form">Sign In</router-link>
          </div>
        </template>
      </DxItem>
      <template #createAccount>
        <div>
          <span class="dx-button-text">
            <DxLoadIndicator
              v-if="loading"
              width="24px"
              height="24px"
              :visible="true"
            />
            <span v-if="!loading">Create a new account</span>
          </span>
        </div>
      </template>
    </DxForm>
  </form>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useRouter } from 'vue-router';
import DxForm, {
  DxItem,
  DxLabel,
  DxButtonItem,
  DxButtonOptions,
  DxCustomRule,
  DxRequiredRule,
  DxEmailRule,
} from 'devextreme-vue/form';
import DxLoadIndicator from 'devextreme-vue/load-indicator';
import notify from 'devextreme/ui/notify';
import auth from '../auth';

const router = useRouter();

const loading = ref(false);
const formData = reactive({
  email: '',
  password: '',
});

const onSubmit = async() => {
  const { email, password } = formData;
  loading.value = true;

  const result = await auth.createAccount(email, password);
  loading.value = false;

  if (result.isOk) {
    router.push('/login-form');
  } else {
    notify(result.message, 'error', 2000);
  }
};

function confirmPassword(e: any) {
  return e.value === formData.password;
}
</script>

<style lang="scss">
@use "../themes/variables.base" as *;

.create-account-form {
  .policy-info {
    margin: 10px 0;
    color: $base-text-color;
    opacity: 0.7;
    font-size: 14px;
    font-style: normal;

    a {
      color: $base-text-color;
      opacity: 0.7;
    }
  }

  .login-link {
    color: $base-accent;
    font-size: 16px;
    text-align: center;
  }
}
</style>
