// React/src/components/reset-password-form/ResetPasswordForm.tsx
import React, { useState, useRef, useCallback } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Form, {
  Item,
  Label,
  ButtonItem,
  ButtonOptions,
  RequiredRule,
  EmailRule,
} from 'devextreme-react/form';
import LoadIndicator from 'devextreme-react/load-indicator';
import notify from 'devextreme/ui/notify';
import { resetPassword } from '../../api/auth';
import './ResetPasswordForm.scss';

const notificationText = 'We\'ve sent a link to reset your password. Check your inbox.';

export default function ResetPasswordForm(): JSX.Element {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const formData = useRef({ email: '', password: '' });

  const handleSubmitAsync = useCallback(async () => {
    const { email } = formData.current;
    setLoading(true);

    const result = await resetPassword(email);
    setLoading(false);

    if (result.isOk) {
      navigate('/login')?.catch(() => {});
      notify(notificationText, 'success', 2500);
    } else {
      notify(result.message, 'error', 2000);
    }
  }, [navigate]);

  const onSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    handleSubmitAsync().catch(() => {});
  }, [handleSubmitAsync]);

  return (
    <form className='reset-password-form' onSubmit={onSubmit}>
      <Form formData={formData.current} disabled={loading}>
        <Item
          dataField='email'
          editorType='dxTextBox'
          editorOptions={emailEditorOptions}
        >
          <RequiredRule message="Email is required" />
          <EmailRule message="Email is invalid" />
          <Label visible={false} />
        </Item>
        <ButtonItem>
          <ButtonOptions
            elementAttr={submitButtonAttributes}
            width='100%'
            type='default'
            useSubmitBehavior={true}
          >
            <span className="dx-button-text">
              {
                loading
                  ? <LoadIndicator width='24px' height='24px' visible={true} />
                  : 'Reset my password'
              }
            </span>
          </ButtonOptions>
        </ButtonItem>
        <Item>
          <div className='login-link'>
            Return to <Link to='/login'>Sign In</Link>
          </div>
        </Item>
      </Form>
    </form>
  );
}

const emailEditorOptions = { stylingMode: 'filled', placeholder: 'Email', mode: 'email' };
const submitButtonAttributes = { class: 'submit-button' };

// Vue/src/views/reset-password-form.vue
<template>
  <form
    class="reset-password-form"
    @submit.prevent="onSubmit"
  >
    <DxForm
      :form-data="formData"
      :disabled="loading"
    >
      <DxItem
        data-field="email"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Email', mode: 'email' }"
      >
        <DxRequiredRule message="Email is required"/>
        <DxEmailRule message="Email is invalid"/>
        <DxLabel :visible="false"/>
      </DxItem>
      <DxButtonItem>
        <DxButtonOptions
          :element-attr="{ class: 'submit-button' }"
          width="100%"
          type="default"
          template="resetTemplate"
          :use-submit-behavior="true"
        />
      </DxButtonItem>
      <DxItem>
        <template #default>
          <div class="login-link">
            Return to <router-link to="/login-form">Sign In</router-link>
          </div>
        </template>
      </DxItem>
      <template #resetTemplate>
        <div>
          <span class="dx-button-text">
            <DxLoadIndicator
              v-if="loading"
              width="24px"
              height="24px"
              :visible="true"
            />
            <span v-if="!loading">Reset my password</span>
          </span>
        </div>
      </template>
    </DxForm>
  </form>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useRouter } from 'vue-router';
import DxForm, {
  DxItem,
  DxLabel,
  DxButtonItem,
  DxButtonOptions,
  DxRequiredRule,
  DxEmailRule,
} from 'devextreme-vue/form';
import DxLoadIndicator from 'devextreme-vue/load-indicator';
import notify from 'devextreme/ui/notify';
import auth from '../auth';

const notificationText =
  "We've sent a link to reset your password. Check your inbox.";

const router = useRouter();

const loading = ref(false);
const formData = reactive({
  email: '',
});

async function onSubmit() {
  const { email } = formData;
  loading.value = true;

  const result = await auth.resetPassword(email);
  loading.value = false;

  if (result.isOk) {
    router.push('/login-form');
    notify(notificationText, 'success', 2500);
  } else {
    notify(result.message, 'error', 2000);
  }
}
</script>

<style lang="scss">
@use "../themes/variables.base" as *;

.reset-password-form {
  .submit-button {
    margin-top: 10px;
  }

  .login-link {
    color: $base-accent;
    font-size: 16px;
    text-align: center;
  }
}
</style>
